apiVersion: v1
kind: Service
metadata:
  name: cilium-agent-metric
  namespace: kube-system
  labels:
    app: cilium
    k8s-app: cilium
spec:
  ports:
    - name: prom # Default endpoint for OpenTelemetry receiver.
      port: 9962
      protocol: TCP
      targetPort: 9962
  selector:
    k8s-app: cilium
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-operator-metric
  namespace: kube-system
  labels:
    name: cilium-operator
    io.cilium/app: operator
spec:
  ports:
    - name: promoperator # Default endpoint for OpenTelemetry receiver.
      port: 9963
      protocol: TCP
      targetPort: 9963
  selector:
    name: cilium-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent-servicemonitor
  namespace: kube-system
  labels:
    app: cilium
    k8s-app: cilium
spec:
  selector:
    matchLabels:
      app: cilium
  endpoints:
    - port: prom
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-operator-servicemonitor
  namespace: kube-system
  labels:
    name: cilium-operator
    io.cilium/app: operator
spec:
  selector:
    matchLabels:
      name: cilium-operator
  endpoints:
    - port: promoperator
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-servicemonitor
  namespace: kube-system
  labels:
    k8s-app: hubble
spec:
  selector:
    matchLabels:
      k8s-app: hubble
  endpoints:
    - port: hubble-metrics
      interval: 15s