apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hubble:
        # NODE_IP is substituted by the collector at runtime
        # the '\' prefix is required only in order for this config to be
        # inlined in the guide and make it easy to paste, i.e. to avoid
        # shell subtituting it
        endpoint: \${NODE_IP}:4244 # unix:///var/run/cilium/hubble.sock
        buffer_size: 100
        include_flow_types:
          # this sets an L7 flow filter, removing this section will
          # disable filtering and result all types of flows being turned
          # into spans;
          # other type filters can be set, the names are same as what's
          # used in 'hubble observe -t <type>'
          traces: ["l7"]
        tls:
          insecure_skip_verify: true
          ca_file: /var/run/hubble-tls/ca.crt
          cert_file: /var/run/hubble-tls/client.crt
          key_file: /var/run/hubble-tls/client.key

    processors:
      batch:
        timeout: 30s
        send_batch_size: 100

    exporters:
      logging:

      otlp:
        endpoint: oteld-collector.otel.svc:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [hubble,otlp]
          processors: [batch]
          exporters: [otlp, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hubble-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - image: ghcr.io/cilium/hubble-otel/otelcol:v0.1.1
          command:
            - "/usr/bin/otelcol-hubble"
            - "--config=/etc/otelcol-contrib/config.yaml"
          name: hubble-collector
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 400Mi
          ports:
            - containerPort: 55679 # Default endpoint for ZPages.
            - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
            - containerPort: 4318 # Default endpoint for Zipkin receiver.
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: hubble-tls
              mountPath: /var/run/hubble-tls
              readOnly: true
          #        - name: otel-collector-secrets
          #          mountPath: /secret
          env:
            # set NODE_IP environment variable using downwards API
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      volumes:
        - configMap:
            name: hubble-collector-conf
          name: otel-collector-config-vol
        - name: hubble-tls
          projected:
            defaultMode: 256
            sources:
              - secret:
                  name: hubble-relay-client-certs
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
                    - key: ca.crt
                      path: ca.crt
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
---
apiVersion: v1
kind: Service
metadata:
  name: hubble-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: otlp # Default endpoint for OpenTelemetry receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otphttp # Default endpoint for Zipkin receiver.
      port: 4318
  selector:
    component: otel-collector
---


